### ISSUE TITLE
Remove cr.hotio.dev from release announcements

### ISSUE THREAD

**Issue by NLZ** [Servarr/discord-bot-cogs#16]
Not sure if this is the right place to raise, but on the Servarr discord in #releases the bot is still writing the decrepated `cr.hotio.dev` docker registry in the docker pull command, probably should be changed.

>mrhotio — 08/20/2023 2:21 AM
Just an FYI, I'll be phasing out the use of Scarf and thus the cr.hotio.dev registry domain, unraid templates and the website are updated to now use ghcr.io as the default. The reason: it's causing too much support questions about adblockers blocking the scarf.sh domain and although not 100% sure about this one, but "unavailable" in Unraid UI......for no benefit at all, the stats are not that interesting to look at :pulliolaughtears: 
https://discord.com/channels/610068305893523457/644100056244551680/1142614476131143831

**Comment by Roxedus** [comment]
This is already fixed for the next release.

**Comment by NLZ** [comment]
Thanks for the info, then I'll just close this
