### ISSUE TITLE
[Parserr] Add absolute episode props for Sonarr

### ISSUE THREAD

**Issue by Qstick** [Servarr/discord-bot-cogs#3]
[AB#98](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/98)

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/149683104-edeabe51-87f1-462b-9b73-c61774a6c798.png)
similar to

**Comment by Qstick** [comment]
Done
